/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cv;
import java.awt.Dimension;
/**
 *
 * @author hrayh
 */
public class menutampilan extends javax.swing.JFrame {

    /**
     * Creates new form menutampilan
     */
    public menutampilan() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Menu Utama");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambarikonlogo1 = new kodegambar.gambarikonlogo();
        dashboard = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        gambarikonatributnilai1 = new kodegambar.gambarikonatributnilai();
        gambarikondatabarang1 = new kodegambar.gambarikondatabarang();
        gambarikonpenjualan1 = new kodegambar.gambarikonpenjualan();
        gambarikonreturn1 = new kodegambar.gambarikonreturn();
        gambarikonsupplier1 = new kodegambar.gambarikonsupplier();
        jPanel2 = new javax.swing.JPanel();
        gambarikonlogo2 = new kodegambar.gambarikonlogo();
        jLabel1 = new javax.swing.JLabel();
        gambarikoncetak1 = new kodegambar.gambarikoncetak();
        gambarikonkriteria1 = new kodegambar.gambarikonkriteria();
        gambarikonkriteria2 = new kodegambar.gambarikonkriteria();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout gambarikonlogo1Layout = new javax.swing.GroupLayout(gambarikonlogo1);
        gambarikonlogo1.setLayout(gambarikonlogo1Layout);
        gambarikonlogo1Layout.setHorizontalGroup(
            gambarikonlogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        gambarikonlogo1Layout.setVerticalGroup(
            gambarikonlogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard.setBackground(new java.awt.Color(51, 51, 255));
        dashboard.setPreferredSize(new java.awt.Dimension(1905, 1129));

        jPanel1.setBackground(new java.awt.Color(14, 41, 84));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        gambarikonatributnilai1.setBackground(new java.awt.Color(14, 41, 84));
        gambarikonatributnilai1.setPreferredSize(new java.awt.Dimension(175, 175));
        gambarikonatributnilai1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikonatributnilai1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikonatributnilai1Layout = new javax.swing.GroupLayout(gambarikonatributnilai1);
        gambarikonatributnilai1.setLayout(gambarikonatributnilai1Layout);
        gambarikonatributnilai1Layout.setHorizontalGroup(
            gambarikonatributnilai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        gambarikonatributnilai1Layout.setVerticalGroup(
            gambarikonatributnilai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        gambarikondatabarang1.setBackground(new java.awt.Color(14, 41, 84));
        gambarikondatabarang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikondatabarang1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikondatabarang1Layout = new javax.swing.GroupLayout(gambarikondatabarang1);
        gambarikondatabarang1.setLayout(gambarikondatabarang1Layout);
        gambarikondatabarang1Layout.setHorizontalGroup(
            gambarikondatabarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        gambarikondatabarang1Layout.setVerticalGroup(
            gambarikondatabarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gambarikonpenjualan1.setBackground(new java.awt.Color(14, 41, 84));
        gambarikonpenjualan1.setPreferredSize(new java.awt.Dimension(175, 175));
        gambarikonpenjualan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikonpenjualan1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikonpenjualan1Layout = new javax.swing.GroupLayout(gambarikonpenjualan1);
        gambarikonpenjualan1.setLayout(gambarikonpenjualan1Layout);
        gambarikonpenjualan1Layout.setHorizontalGroup(
            gambarikonpenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        gambarikonpenjualan1Layout.setVerticalGroup(
            gambarikonpenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        gambarikonreturn1.setBackground(new java.awt.Color(14, 41, 84));
        gambarikonreturn1.setPreferredSize(new java.awt.Dimension(175, 175));
        gambarikonreturn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikonreturn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikonreturn1Layout = new javax.swing.GroupLayout(gambarikonreturn1);
        gambarikonreturn1.setLayout(gambarikonreturn1Layout);
        gambarikonreturn1Layout.setHorizontalGroup(
            gambarikonreturn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gambarikonreturn1Layout.setVerticalGroup(
            gambarikonreturn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        gambarikonsupplier1.setBackground(new java.awt.Color(14, 41, 84));
        gambarikonsupplier1.setPreferredSize(new java.awt.Dimension(175, 175));
        gambarikonsupplier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikonsupplier1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikonsupplier1Layout = new javax.swing.GroupLayout(gambarikonsupplier1);
        gambarikonsupplier1.setLayout(gambarikonsupplier1Layout);
        gambarikonsupplier1Layout.setHorizontalGroup(
            gambarikonsupplier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        gambarikonsupplier1Layout.setVerticalGroup(
            gambarikonsupplier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout gambarikonlogo2Layout = new javax.swing.GroupLayout(gambarikonlogo2);
        gambarikonlogo2.setLayout(gambarikonlogo2Layout);
        gambarikonlogo2Layout.setHorizontalGroup(
            gambarikonlogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        gambarikonlogo2Layout.setVerticalGroup(
            gambarikonlogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CV AGA JAYA CENTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambarikonlogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(410, 410, 410)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarikonlogo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gambarikoncetak1.setBackground(new java.awt.Color(14, 41, 84));
        gambarikoncetak1.setPreferredSize(new java.awt.Dimension(175, 175));
        gambarikoncetak1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikoncetak1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikoncetak1Layout = new javax.swing.GroupLayout(gambarikoncetak1);
        gambarikoncetak1.setLayout(gambarikoncetak1Layout);
        gambarikoncetak1Layout.setHorizontalGroup(
            gambarikoncetak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        gambarikoncetak1Layout.setVerticalGroup(
            gambarikoncetak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        gambarikonkriteria1.setBackground(new java.awt.Color(14, 41, 84));
        gambarikonkriteria1.setPreferredSize(new java.awt.Dimension(175, 175));
        gambarikonkriteria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikonkriteria1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikonkriteria1Layout = new javax.swing.GroupLayout(gambarikonkriteria1);
        gambarikonkriteria1.setLayout(gambarikonkriteria1Layout);
        gambarikonkriteria1Layout.setHorizontalGroup(
            gambarikonkriteria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        gambarikonkriteria1Layout.setVerticalGroup(
            gambarikonkriteria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        gambarikonkriteria2.setBackground(new java.awt.Color(14, 41, 84));
        gambarikonkriteria2.setPreferredSize(new java.awt.Dimension(175, 175));
        gambarikonkriteria2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarikonkriteria2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gambarikonkriteria2Layout = new javax.swing.GroupLayout(gambarikonkriteria2);
        gambarikonkriteria2.setLayout(gambarikonkriteria2Layout);
        gambarikonkriteria2Layout.setHorizontalGroup(
            gambarikonkriteria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        gambarikonkriteria2Layout.setVerticalGroup(
            gambarikonkriteria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Return");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cetak");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Penjualan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nilai Hitung AHP");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kriteria");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sub Kriteria");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gambarikondatabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gambarikoncetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(63, 63, 63)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7))
                                    .addComponent(gambarikonatributnilai1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(gambarikonpenjualan1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gambarikonreturn1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(gambarikonkriteria1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gambarikonsupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gambarikonkriteria2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel8)
                                .addGap(192, 192, 192)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(jLabel10)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gambarikonreturn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gambarikondatabarang1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gambarikonpenjualan1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(gambarikonsupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gambarikoncetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gambarikonatributnilai1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gambarikonkriteria1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gambarikonkriteria2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(206, 206, 206))
        );

        dashboard.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1932, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gambarikonsupplier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikonsupplier1MouseClicked
        formsupplier dc = new formsupplier();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_gambarikonsupplier1MouseClicked

    private void gambarikonreturn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikonreturn1MouseClicked
        formreturn dc = new formreturn();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_gambarikonreturn1MouseClicked

    private void gambarikonpenjualan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikonpenjualan1MouseClicked
        formpenjualan dc = new formpenjualan();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_gambarikonpenjualan1MouseClicked

    private void gambarikondatabarang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikondatabarang1MouseClicked
        formdatabarang dc = new formdatabarang();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_gambarikondatabarang1MouseClicked

    private void gambarikonatributnilai1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikonatributnilai1MouseClicked
        hitung dc = new hitung();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_gambarikonatributnilai1MouseClicked

    private void gambarikonkriteria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikonkriteria1MouseClicked
         kriteria dc = new kriteria();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_gambarikonkriteria1MouseClicked

    private void gambarikonkriteria2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikonkriteria2MouseClicked
       subkriteria dc = new subkriteria();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_gambarikonkriteria2MouseClicked

    private void gambarikoncetak1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarikoncetak1MouseClicked
      cetak dc = new cetak();
        dashboard.add(dc);
        Dimension gs = dashboard.getSize();
        Dimension cs = dc.getSize();
        dc.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        dc.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_gambarikoncetak1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menutampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menutampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menutampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menutampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menutampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dashboard;
    private kodegambar.gambarikonatributnilai gambarikonatributnilai1;
    private kodegambar.gambarikoncetak gambarikoncetak1;
    private kodegambar.gambarikondatabarang gambarikondatabarang1;
    private kodegambar.gambarikonkriteria gambarikonkriteria1;
    private kodegambar.gambarikonkriteria gambarikonkriteria2;
    private kodegambar.gambarikonlogo gambarikonlogo1;
    private kodegambar.gambarikonlogo gambarikonlogo2;
    private kodegambar.gambarikonpenjualan gambarikonpenjualan1;
    private kodegambar.gambarikonreturn gambarikonreturn1;
    private kodegambar.gambarikonsupplier gambarikonsupplier1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
